### ISSUE TITLE
No autocomplete in `meson.build` file

### ISSUE THREAD

**Issue by synalice** [mesonbuild/vscode-meson#271]
I've installed this extension and it prompted me to install an LSP, so it should be installed (how do I verify that?).

Unfortunately, there is still no autocomplete for `meson.build` files. I get suggestions only for commands that were already entered previously in any of the files. No error squiggly lines either. Why is that?

So time ago I had the exact same setup and everything worked fine. 

Meson is installed via pip, the Identifier of this extension is `mesonbuild.mesonbuild`. It's the only meson VSCode extension installed. I also have muon installed. I've build it from source.
```
muon 0.3.1
meson compatibility version 1.5.99
enabled features:
  samurai
```
Downloading [mesonlsp](https://github.com/JCWasmx86/mesonlsp/releases/tag/v4.3.7) and manually adding its binary to `/urs/bin` has no effect, still no autocomplete.

The is no `mesonbuild.*` settings set in my VSCode settings.json config. 

Pls help :(

**Comment by synalice** [comment]
```console
$ mesonlsp --help
Usage: mesonlsp [<options>] [<paths> ...]

ARGUMENTS:
  <paths>	Path to parse

OPTIONS:
--path <path>			Path to parse 100x times (default: ./meson.build)
--lsp        			Start language server using stdio
--wrap <wrapFile>		Extract and parse this wrap file
--wrap-output <dir>		Set the directory into that the given wraps should be extracted.
--wrap-package-files <dir>	Set the location of the package files containing auxiliary files
--full 				Fully setup and check a project (Includes subprojects)
--version    			Print version
--help       			Print this help
$ mesonlsp --version
mesonlsp version:       v4.3.7 (v4.3.7)
Using C compiler:       gcc 13.2.1
Using C++ compiler:     gcc 13.2.1
Linker:                 ld.bfd
```
```console
$ ps -aux|grep mesonlsp
user  405206  0.0  0.0  36008  7552 ?        Sl   15:40   0:00 /home/user/.config/Code/User/globalStorage/mesonbuild.mesonbuild/lsp/mesonlsp --lsp
user  405478  0.0  0.0   9220  2560 pts/1    S+   15:43   0:00 grep mesonlsp
```

The VSCode `OUTPUT` panel is alive and well. Flourishing even, there are a lot of different outputs there. Interesting things happen when I run `Format Document` command (<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd>). If there are syntax errors, I get VSCode error in the bottom-right corner.

![image](https://github.com/user-attachments/assets/2e7533d5-cc09-4c3d-88a1-5281f628f9ef)

The output in  question:
```
[ INFO ] AbstractLanguageServer - ../src/libls/ls.cpp:70: Received request: textDocument/formatting 
/home/user/project/meson.build:61:53: error expected ) not =
[ ERROR ] formatting - ../src/liblangserver/formatting.cpp:62: Failed to format
[ DEBUG ] cxathrow - ../src/libcxathrow/shared.cpp:16: Exception of type std::runtime_error 
[ DEBUG ] cxathrow - ../src/libcxathrow/shared.cpp:30:   what(): Failed to format 
[ DEBUG ] cxathrow - ../src/libcxathrow/backtrace_libunwind.cpp:33: #0: __wrap___cxa_throw+0x35f [0x78e89f] 
[ DEBUG ] cxathrow - ../src/libcxathrow/backtrace_libunwind.cpp:33: #1: LanguageServer::formatting(DocumentFormattingParams&) [clone .cold]+0xd9 [0x4950f5] 
[ DEBUG ] cxathrow - ../src/libcxathrow/backtrace_libunwind.cpp:33: #2: AbstractLanguageServer::handleRequest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nlohmann::json_abi_v3_11_2::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >, nlohmann::json_abi_v3_11_2::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >)+0x108d [0x710d8d] 
[ DEBUG ] cxathrow - ../src/libcxathrow/backtrace_libunwind.cpp:33: #3: std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, std::thread::_Invoker<std::tuple<void (jsonrpc::JsonRpcHandler::*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nlohmann::json_abi_v3_11_2::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >, nlohmann::json_abi_v3_11_2::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >), std::shared_ptr<jsonrpc::JsonRpcHandler>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nlohmann::json_abi_v3_11_2::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >, nlohmann::json_abi_v3_11_2::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > > > >, void> >::_M_invoke(std::_Any_data const&)+0xd9 [0x695ff9] 
[ DEBUG ] cxathrow - ../src/libcxathrow/backtrace_libunwind.cpp:33: #4: std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)+0x35 [0x68b325] 
[ DEBUG ] cxathrow - ../src/libcxathrow/backtrace_libunwind.cpp:33: #5: __pthread_once_full+0x37 [0xd0391e] 
[ DEBUG ] cxathrow - ../src/libcxathrow/backtrace_libunwind.cpp:39: #6: 0x77a91bf58068
[Error - 4:30:00 PM] Request textDocument/formatting failed.
  Message: Failed to format
  Code: -32603
[ INFO ] AbstractLanguageServer - ../src/libls/ls.cpp:70: Received request: textDocument/inlayHint 
```
I did not restart the server manually, it recovers automatically it seems. After fixing syntax error in `meson.build` file (the error is NOT being highlighted with squiggles btw) and running `Format Document` command again the output is this:
```
[ INFO ] AbstractLanguageServer - ../src/libls/ls.cpp:70: Received request: textDocument/formatting 
[ INFO ] AbstractLanguageServer - ../src/libls/ls.cpp:18: Received notification textDocument/didChange 
[ INFO ] AbstractLanguageServer - ../src/libls/ls.cpp:70: Received request: textDocument/inlayHint 
[ INFO ] AbstractLanguageServer - ../src/libls/ls.cpp:70: Received request: textDocument/foldingRange 
[ INFO ] AbstractLanguageServer - ../src/libls/ls.cpp:70: Received request: textDocument/semanticTokens/full 
[ INFO ] AbstractLanguageServer - ../src/libls/ls.cpp:70: Received request: textDocument/documentSymbol 
[ INFO ] AbstractLanguageServer - ../src/libls/ls.cpp:70: Received request: textDocument/documentSymbol 
[ INFO ] AbstractLanguageServer - ../src/libls/ls.cpp:70: Received request: textDocument/inlayHint
```

**Comment by synalice** [comment]
```console
$ /home/user/.config/Code/User/globalStorage/mesonbuild.mesonbuild/lsp/mesonlsp --help
Usage: mesonlsp [<options>] [<paths> ...]

ARGUMENTS:
  <paths>	Path to parse

OPTIONS:
--path <path>			Path to parse 100x times (default: ./meson.build)
--lsp        			Start language server using stdio
--wrap <wrapFile>		Extract and parse this wrap file
--wrap-output <dir>		Set the directory into that the given wraps should be extracted.
--wrap-package-files <dir>	Set the location of the package files containing auxiliary files
--full 				Fully setup and check a project (Includes subprojects)
--version    			Print version
--help       			Print this help
$ /home/user/.config/Code/User/globalStorage/mesonbuild.mesonbuild/lsp/mesonlsp --version
mesonlsp version:       v4.3.3 (v4.3.3)
Using C compiler:       gcc 13.2.1
Using C++ compiler:     gcc 13.2.1
Linker:                 ld.bfd
```

**Comment by synalice** [comment]
What weird is that `mesonlsp` says I am using `gcc 13.2.1` while I actually only have `gcc 11.4.0`...
```console
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.4.0-1ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)
```

**Comment by synalice** [comment]
I've found the issue. It is... Well, I wonder if it is intentional?

Here is the log from `OUTPUT` panel:
```
[ INFO ] analyze::mesontree - ../src/libanalyze/mesontree.cpp:203: Parsing root (/home/user/project) 
[ WARN ] analyze::mesontree - ../src/libanalyze/mesontree.cpp:195: No meson.build file in /home/user/project
```

The reason for lsp not working was the fact that I don't have `meson.build` file at the root of the directory that is opened in VSCode. In VSCode I open `/home/user/project` but the actual top-level `meson.build` file is inside a sub-directory (as if it was a git sub-module, basically) — `/home/user/project/project/meson.build`.

Basically, my file-structure is this:
```
project  (/home/user/project)  <- This is opened in VSCode
│
├── <files-unrelated-to-source-code>
│
└── project  (/home/user/project/project)
    ├── include
    │   ├── file.h
    │   └── meson.build
    ├── meson.build  (/home/user/project/project/meson.build)  <- Top-level meson.build file
    └── src
        ├── file.c
        └── meson.build
```

The issue completely disappears when in VSCode I open `/home/user/project/project`  instead of `/home/user/project`. But this makes it impossible to see `<files-unrelated-to-source-code>`. Not the best solution out there.

I could move `<files-unrelated-to-source-code>` inside `/home/user/project/project` and make the file structure more flat, but is there something else I can do?

**Comment by synalice** [comment]
Well, then the issue is solved. Huge thank you, you really helped a lot ❤️

**Comment by hi0t** [comment]
@synalice Why close? The bug still exists. I also encountered the same bug and couldn't figure out what was going on. The vscode extension allows using meson.build in a non-root directory and the languge server doesn't support it.

**Comment by synalice** [comment]
> The vscode extension allows using meson.build in a non-root directory and the languge server doesn't support it.

Oh, then its a bug, yeah. I wasn't sure if it was intentional or not. Reopened the issue.

**Comment by hi0t** [comment]
I see that mesonlsp has a --path argument. Probably the extension should pass the path to the root directory if the user explicitly selects it.
